module Karma
  module Operations
    def self.metrics(cluster : Cluster) : String
      String.build do |io|
        io << "# TYPE karma_uptime_seconds gauge\n"
        io << "karma_uptime_seconds #{uptime_seconds}\n"
        io << "# TYPE karma_trees gauge\n"
        io << "karma_trees #{cluster.tree_count}\n"
        io << "# TYPE karma_keys gauge\n"
        io << "karma_keys #{cluster.key_count}\n"
        io << "# TYPE karma_dumps gauge\n"
        io << "karma_dumps #{Karma::Backup.dumps(Karma.config.dump_dir).size}\n"
        io << "# TYPE karma_wal_bytes gauge\n"
        io << "karma_wal_bytes #{wal_bytes}\n"
        io << "# TYPE karma_memory_bytes gauge\n"
        io << "karma_memory_bytes #{GC.stats.heap_size}\n"
        io << "# TYPE karma_commands_total counter\n"
        io << "karma_commands_total #{command_count}\n"
        io << "# TYPE karma_errors_total counter\n"
        io << "karma_errors_total #{error_count}\n"
        io << "# TYPE karma_protocol_v1_requests_total counter\n"
        io << "karma_protocol_v1_requests_total #{legacy_request_count}\n"
        io << "# TYPE karma_query_timeouts_total counter\n"
        io << "karma_query_timeouts_total #{query_timeout_count}\n"
        io << "# TYPE karma_batch_reads_total counter\n"
        io << "karma_batch_reads_total #{batch_read_count}\n"
        io << "# TYPE karma_batch_read_keys_total counter\n"
        io << "karma_batch_read_keys_total #{batch_read_key_count}\n"
        io << "# TYPE karma_batch_writes_total counter\n"
        io << "karma_batch_writes_total #{batch_write_count}\n"
        io << "# TYPE karma_batch_write_items_total counter\n"
        io << "karma_batch_write_items_total #{batch_write_item_count}\n"
        io << "# TYPE karma_retention_operations_total counter\n"
        io << "karma_retention_operations_total #{retention_count}\n"
        io << "# TYPE karma_compactions_total counter\n"
        io << "karma_compactions_total #{compact_count}\n"
        io << "# TYPE karma_command_latency_ms gauge\n"
        io << "karma_command_latency_ms #{last_latency_ms}\n"
        io << "# TYPE karma_command_latency_ms_average gauge\n"
        io << "karma_command_latency_ms_average #{average_latency_ms}\n"
        ingest_metrics = Karma::Ingest.metrics
        io << "# TYPE karma_ingest_active_streams gauge\n"
        io << "karma_ingest_active_streams #{ingest_metrics[:active_streams]}\n"
        io << "# TYPE karma_ingest_chunks_applied_total counter\n"
        io << "karma_ingest_chunks_applied_total #{ingest_metrics[:chunks_applied]}\n"
        io << "# TYPE karma_ingest_chunks_skipped_total counter\n"
        io << "karma_ingest_chunks_skipped_total #{ingest_metrics[:chunks_skipped]}\n"
        io << "# TYPE karma_ingest_chunks_rejected_total counter\n"
        io << "karma_ingest_chunks_rejected_total #{ingest_metrics[:chunks_rejected]}\n"
        io << "# TYPE karma_ingest_items_applied_total counter\n"
        io << "karma_ingest_items_applied_total #{ingest_metrics[:items_applied]}\n"
        io << "# TYPE karma_ingest_chunk_latency_ms gauge\n"
        io << "karma_ingest_chunk_latency_ms #{ingest_metrics[:latency_ms_last]}\n"
        io << "# TYPE karma_ingest_chunk_latency_ms_average gauge\n"
        io << "karma_ingest_chunk_latency_ms_average #{ingest_metrics[:latency_ms_average]}\n"
      end
    end
  end
end
